version: "3.8"

services:
  nginx:
    container_name: nginx
    build: ./docker/nginx
    ports:
      - "${NGINX_HOST_PORT}:${NGINX_PORT}"
    env_file:
      - ./env/.nginx.dev.env
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./docker/nginx/logs:/var/log/nginx/
    networks:
      - dev_network

  front:
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    container_name: front
    hostname: front
    stdin_open: true
    tty: true
    ports:
      - ${FRONT_HOST_PORT}:${FRONT_PORT}
    volumes:
      - ./client:/node/client

networks:
  dev_network:
    external: true
