version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./docker/nginx
    ports:
      - '80:80'
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/logs:/var/log/nginx
  front:
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    container_name: front
    hostname: front
    stdin_open: true
    tty: true
    ports:
      - 5000:5000
    volumes:
      - .:/home/node/client
