version: "3.8"

services:
  nginx:
    ports:
      - "${NGINX_HOST_PORT}:${NGINX_PORT}"
    env_file:
      - ./env/.nginx.dev.env
    networks:
      - dev_network

  front:
    ports:
      - ${FRONT_HOST_PORT}:${FRONT_PORT}
    volumes:
      - ./client:/node/client

networks:
  dev_network:
    external: true
