version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./docker/nginx
    ports:
      - '${NGINX_HOST_PORT}:${NGINX_PORT}'
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/logs:/var/log/nginx

  front:
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    container_name: front
    hostname: front
    stdin_open: true
    tty: true
    ports:
      - ${FRONT_HOST_PORT}:${FRONT_PORT}
    volumes:
      - .:/home/node/client

networks:
  default:
    external: true
    name: dev_network
