version: '3.8'

services:
  nginx:
    image: nginx:1.21.4
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ../dist:/usr/share/nginx/html
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
